# .readthedocs.yml

# Required
version: 2

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "miniconda-latest"

# Conda environment file
conda:
  environment: linux_env.yml

# Sphinx configuration
sphinx:
  configuration: docs_core/conf.py

# Define the type of documentation to be built
# formats:
  # - html
  # - pdf
