# .readthedocs.yml

# Required
version: 2

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    conda: "latest"

# Conda environment file
conda:
  file: linux_env.yml

# Sphinx configuration
sphinx:
  builder: html
  configuration: docs_core/conf.py

# Define the type of documentation to be built
# formats:
  # - html
  # - pdf

# Additional configurations
submodules:
  include: true

# Custom build commands
commands:
  - echo "Custom pre-build command"
  - make html

# Environment variables
env:
  MY_VARIABLE: "value"

# Notifications
notifications:
  email:
    - lukas.lodes@gmail.com
