name: Tests (Self-hosted)

on: push
jobs:
  run-tests:
    name: Tests
    runs-on: "self-hosted"
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: run-tests
      run: |
        conda activate ManPy
        conda info
        conda list
        python -m unittest discover manpy/tests
